"""Deleted level colum in Student

Revision ID: a91eb86f95f4
Revises: fa70f7d2a3a7
Create Date: 2023-09-07 22:28:17.042398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a91eb86f95f4'
down_revision: Union[str, None] = 'fa70f7d2a3a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'level')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('level', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
