"""create tables

Revision ID: fa70f7d2a3a7
Revises: 35fc90037c49
Create Date: 2023-09-07 21:33:45.902746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa70f7d2a3a7'
down_revision: Union[str, None] = '35fc90037c49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school', sa.Column('name', sa.String(), nullable=False))
    op.add_column('school', sa.Column('location', sa.String(), nullable=False))
    op.add_column('students', sa.Column('name', sa.Integer(), nullable=False))
    op.add_column('students', sa.Column('grade', sa.String(), nullable=False))
    op.add_column('students', sa.Column('time_in', sa.DateTime(), nullable=True))
    op.add_column('students', sa.Column('level', sa.String(), nullable=False))
    op.add_column('teachers', sa.Column('name', sa.Integer(), nullable=False))
    op.add_column('teachers', sa.Column('subjects', sa.String(), nullable=False))
    op.add_column('teachers', sa.Column('teaching_level', sa.String(), nullable=False))
    op.add_column('teachers', sa.Column('time_in', sa.DateTime(), nullable=True))
    op.add_column('workers', sa.Column('name', sa.Integer(), nullable=False))
    op.add_column('workers', sa.Column('time_in', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workers', 'time_in')
    op.drop_column('workers', 'name')
    op.drop_column('teachers', 'time_in')
    op.drop_column('teachers', 'teaching_level')
    op.drop_column('teachers', 'subjects')
    op.drop_column('teachers', 'name')
    op.drop_column('students', 'level')
    op.drop_column('students', 'time_in')
    op.drop_column('students', 'grade')
    op.drop_column('students', 'name')
    op.drop_column('school', 'location')
    op.drop_column('school', 'name')
    # ### end Alembic commands ###
